last updates to work well with TADbit
3DGenomes/TADdyn pull request #5
Opened 2020-11-04 16:04 UTC by julenmendieta

2020-11-04 17:33 UTC, david-castillo requested changes
Yo había pensado algo incluso más fácil. Poner esto en la línea 574 

    ```
    results = []
    initial_models = initial_conformation
    if not initial_models:
        initial_models = []
    def collect_result(result):
        results.append((result[0], result[1]))
        if not initial_conformation:
            k_folder = lammps_folder + 'lammps_' + str(result[0]) + '/'       
            initial_models.append(read_conformation_file('%sinitial_conformation.dat' % k_folder))

```

y borrar de la línea 712 a 715

2020-11-05 10:36 UTC, julenmendieta commented
Como prefieras. Lo único no habria que borrar lo de las lineas 712 a 715,
sino actualizarlo para que reordene initial_models en el mismo orden que
los modelos por objective function no?

A parte de esto, ¿como de bien visto está el ampliar una lista (initial_models)
que no se incluye entre los parametros de la función? ¿Seria como una
variable global?



El mié., 4 de noviembre de 2020 18:33, david-castillo <
notifications@github.com> escribió:

> *@david-castillo* requested changes on this pull request.
>
> Yo había pensado algo incluso más fácil. Poner esto en la línea 574
>
> ```
>
> results = []
>
> initial_models = initial_conformation
>
> if not initial_models:
>
>     initial_models = []
>
> def collect_result(result):
>
>     results.append((result[0], result[1]))
>
>     if not initial_conformation:
>
>         k_folder = lammps_folder + 'lammps_' + str(result[0]) + '/'
>
>         initial_models.append(read_conformation_file('%sinitial_conformation.dat' % k_folder))
>
>
>
>
> y borrar de la línea 712 a 715
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/3DGenomes/TADdyn/pull/5#pullrequestreview-523586345>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACZAHT2P3GL3MV3PXWSMZJTSOGGADANCNFSM4TKHMDPA>
> .
>

2020-11-05 11:52 UTC, david-castillo commented
Tienes razón, al final va a ser el mismo trabajo, no?

2020-11-05 12:14 UTC, julenmendieta commented
Yo creo que si, además que esto ya está hecho y lo he probado generando los
modelos xD. A no ser que tengas claro que run_lammps es mejor que devuelva
solo dos parametros, se puede quedar como está hasta que Marco mire lo de
los time points. Igual entonces vemos que hay que cambiarlo para que valga
para los dos casos.

El jue., 5 nov. 2020 a las 12:53, david-castillo (<notifications@github.com>)
escribió:

> Tienes razón, al final va a ser el mismo trabajo, no?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/3DGenomes/TADdyn/pull/5#issuecomment-722330508>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACZAHT6E2ECNMGE4GSXOZBTSOKG2HANCNFSM4TKHMDPA>
> .
>

2020-11-05 12:46 UTC, merged